name: Docker Image

# Controls when the action will run. 
on:
  # When a release is published
  release:
    types: [published]

  # Trigger on push for latest build ignoring tag pushes
  push:
    tags:
      - '!**'
    branches:
      - main
      
  # Manually trigger for a release
  workflow_dispatch:
    inputs:
      tag:
        description: 'What tag should be used for the release.'
        required: true      

jobs:

  image_keycloak:
  
    env:
      PLATFORM: linux/amd64,linux/arm64,linux/arm/v7
      TAG: latest

    runs-on: ubuntu-latest

    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Set tag
        run: echo "TAG=${{ github.event.release.tag_name || github.event.inputs.tag || env.TAG }}" >> $GITHUB_ENV
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: grant execute permission for gradlew
        run: chmod +x gradlew
      - name: build with Gradle
        run: ./gradlew installDist
      - name: set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true
      - name: available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: login to docker hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin
      - name: build and push images
        run: |
          docker build --build-arg GIT_COMMIT=${{ github.sha }} --push --platform $PLATFORM -t openremote/keycloak:$TAG .
