name: build keycloak Docker image and push to it dockerhub

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
      - keycloak/**
      - .github/workflows/keycloak.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PLATFORM: linux/amd64,linux/arm64

jobs:

  image_keycloak:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: grant execute permission for gradlew
        run: chmod +x gradlew
      - name: build with Gradle
        run: ./gradlew :keycloak:installDist
      - name: set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true
      - name: available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: login to docker hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin
      - name: build and push images
        run: |
          docker build --push --platform $PLATFORM -t openremote/keycloak:latest keycloak
